sudo: required
language: generic
services:
    - docker

#execute commands before run test suites
before_install:
    - docker build -t nevaehtang/docker-react -f Dockerfile.dev .


#execute commands to run test suites
script:
    - docker run -e CI=true nevaehtang/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env-1"
    bucket_name: "elasticbeanstalk-us-east-2-355716905408"
    bucket_path: "docker-react"
    # only deploy to AWS when we push code to master
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY


